### ISSUE TITLE
Or-gotcha

### ISSUE THREAD

**Issue by tagptroll1** [RohanJnr/Gator-Bot#1]
https://github.com/RohanJnr/Gator-Bot/blob/d6d01562a79feb5f4a9c9510eda603a8475fc2e0/cogs/update_sheets.py#L25

If this is meant to check if admin[0] to admin[2] is in the listcomprehension then this will not work as expected.  If admin[0] or admin[1] has *any* value then this statement is always true.

**Comment by tagptroll1** [comment]
Alternative you could do is check if `any(role.id in admin_ids for role in ctx.author.roles)` assuming it's rewrite and using the `ctx.author` shortcut

**Comment by tagptroll1** [comment]
Revisit these as well  
https://github.com/RohanJnr/Gator-Bot/blob/master/cogs/update_sheets.py#L38  
https://github.com/RohanJnr/Gator-Bot/blob/master/cogs/update_sheets.py#L53  
https://github.com/RohanJnr/Gator-Bot/blob/master/cogs/update_sheets.py#L64

**Comment by RohanJnr** [comment]
i have changed the if statement where ever possible
